// <auto-generated />
using API_MOVIE.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_MOVIE.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_MOVIE.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = " Pelicula nro 1 de la cartelera",
                            Titulo = "12 años de esclavitud",
                            Url = "https://imagenes.canalrcn.com/lomaslike/preprate-para-conocer-los-12-aos-de-esclavitud-de-solomon-por-el-canal-rcn-este-domingo.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = " Pelicula nro 2 de la cartelera",
                            Titulo = "Dos buenos tipos",
                            Url = "https://pics.filmaffinity.com/Dos_buenos_tipos-118256026-large.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Auxilio abuela me pico una araña",
                            Titulo = "Spiderman 2",
                            Url = "https://static.wikia.nocookie.net/blackcoffe/images/1/1f/Spiderman2.jpg/revision/latest?cb=20120611025348&path-prefix=es"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
